using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_BOOKS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_BOOKS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_BOOKS
    {
      public const int TITLE = 1;
      public const int AUTHOR_ID = 2;
      public const int ISBN = 3;
      public const int DEPT = 4;
      public const int GENRE = 5;
      public const int MEDIA = 6;
      public const int PUBLISHER_ID = 7;
      public const int PUB_YEAR = 8;
      public const int SALE_PRICE = 8;
      public const int SALE_PRICE_INTL = 8;
      public const int STOCK_LEVEL = 9;
      public const int MIN_ORDER = 10;
      public const int ON_ORDER = 11;
      public const int TAX_CODE = 12;
      public const int SUPPLIER_ID = 13;
      public const int PURCH_PRICE = 14;
      public const int PURCH_PRICE_INTL = 14;
      public const int RESERVED = 15;
      public const int SUPPLIER_CODE = 16;
      public const int LONG_DESCRIPTION = 20;
    }
}
