using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_CLIENTS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_CLIENTS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_CLIENTS
    {
      public const int SURNAME = 1;
      public const int FORENAME = 2;
      public const int ADDRESS = 3;
      public const int COUNTRY = 4;
      public const int TERRITORY_ID = 5;
      public const int JOIN_DATE = 6;
      public const int ACCOUNT_HELD = 7;
      public const int ACCOUNT_STATUS = 7;
    }
}
