using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_ORDERS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_ORDERS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_ORDERS
    {
      public const int CLIENT_ID = 1;
      public const int ORDER_STATUS = 2;
      public const int DELIV_ADDR = 3;
      public const int INSTRUCTIONS = 3;
      public const int ORIGIN_CODE = 4;
      public const int SHIP_ID = 5;
      public const int SHIP_COST = 6;
      public const int DESPATCH_DATE = 7;
      public const int SALES_ID = 8;
      public const int BOOK_ID = 10;
      public const int QTY = 11;
      public const int PRICE = 12;
      public const int PRICE_INTL = 12;
      public const int TAX_CODE = 13;
      public const int DESPATCHED = 14;
      public const int PROMO_ID = 15;
      public const int TAX_RATE = 16;
    }
}
