using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_PAYMENTS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_PAYMENTS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_PAYMENTS
    {
      public const int PAY_DATE = 1;
      public const int CLIENT_ID = 2;
      public const int AMOUNT = 3;
      public const int AMOUNT_INTL = 3;
    }
}
