using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_PURCHASES
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_PURCHASES
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_PURCHASES
    {
      public const int ORDER_DATE = 1;
      public const int SUPPLIER_ID = 2;
      public const int SHIP_COST = 3;
      public const int SHIP_COST_INTL = 3;
      public const int DELIV_DATE = 4;
      public const int BOOK_ID = 10;
      public const int ISBN = 11;
      public const int SUPPLIER_CODE = 11;
      public const int PRICE = 12;
      public const int PRICE_INTL = 12;
      public const int TAX_CODE = 13;
      public const int ORDER_QTY = 14;
      public const int RECEIVE_QTY = 14;
      public const int REJECT_QTY = 15;
    }
}
