using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_PUBLISHERS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_PUBLISHERS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_PUBLISHERS
    {
      public const int FULLNAME = 1;
      public const int BOOK_IDS = 2;
    }
}
