using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_PROFILES
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_PROFILES
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_PROFILES
    {
      public const int DEPT_GENRE = 1;
      public const int COUNTS = 2;
    }
}
