using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_PROMOTIONS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_PROMOTIONS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_PROMOTIONS
    {
      public const int SHORT_DESCRIPTION = 1;
      public const int DISCOUNT_PCT = 2;
      public const int START_DATE = 3;
      public const int END_DATE = 4;
      public const int BOOK_ID = 5;
      public const int TITLE_ID = 5;
      public const int MIN_QTY = 6;
    }
}
