using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_PERSONNEL
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_PERSONNEL
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_PERSONNEL
    {
      public const int SURNAME = 1;
      public const int FORENAME = 2;
      public const int JOB_TITLE = 3;
      public const int MANAGER = 4;
    }
}
