using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_SHIPPING
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_SHIPPING
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_SHIPPING
    {
      public const int SHORT_DESCRIPTION = 1;
      public const int COST = 2;
      public const int SHIPPER = 2;
      public const int BASE_RATE = 3;
    }
}
