using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_SALESTAX
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_SALESTAX
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_SALESTAX
    {
      public const int SHORT_DESCRIPTION = 1;
      public const int RATE = 2;
    }
}
