using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_SUPPLIERS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_SUPPLIERS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_SUPPLIERS
    {
      public const int FULLNAME = 1;
      public const int ADDRESS = 2;
      public const int PHONE = 3;
      public const int FAX = 4;
      public const int EMAIL = 5;
      public const int SHIP_COST = 10;
    }
}
