using System;
using System.Collections.Generic;
using System.Text;
//------------------------------------------------------------------------------
//  Include file for : U2_TARGETS
//  Generated on     : 21 APR 2018
//  Generated by     : MakeTable script books.tables U2_TARGETS
//------------------------------------------------------------------------------
namespace u2_books.model
{
    public partial class U2_TARGETS
    {
      public const int PERIOD = 1;
      public const int TARGET = 2;
    }
}
