!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : BOOK_IMPORTS
!  Generated on     : 01 JUN 2010
!  Generated by     : MakeTable script book_scripts tables
!------------------------------------------------------------------------------
EQU BOOK_IMPORTS.TITLE TO 1
EQU BOOK_IMPORTS.AUTHOR TO 2
EQU BOOK_IMPORTS.PUBLISHER TO 3
EQU BOOK_IMPORTS.MEDIA TO 4
EQU BOOK_IMPORTS.ISBN TO 5
EQU BOOK_IMPORTS.PUBLISHED TO 6
EQU BOOK_IMPORTS.SYNOPSIS TO 7
EQU BOOK_IMPORTS.RATING TO 8
EQU BOOK_IMPORTS.REVIEWS TO 9
EQU BOOK_IMPORTS.PRICE TO 10
EQU BOOK_IMPORTS.DEPT TO 11
EQU BOOK_IMPORTS.GENRE TO 12
