!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_AUTHORS
!  Generated on     : 02 MAY 2018
!  Generated by     : MakeTable script books.tables.safe U2_AUTHORS
!------------------------------------------------------------------------------
EQU U2_AUTHORS.FULLNAME TO 1
EQU U2_AUTHORS.BOOK_IDS TO 2
