!INCLUDE
! Define the virtual Book Data send and returned by the subroutines
EQU U2_BOOKDATA.TITLE TO 1
EQU U2_BOOKDATA.AUTHOR_ID TO 2
EQU U2_BOOKDATA.AUTHOR_NAME To 3
EQU U2_BOOKDATA.ISBN TO 4
EQU U2_BOOKDATA.DEPT TO 5
EQU U2_BOOKDATA.GENRE TO 6
EQU U2_BOOKDATA.MEDIA TO 7
EQU U2_BOOKDATA.PUBLISHER_ID TO 8
EQU U2_BOOKDATA.PUBLISHER_NAME TO 9
EQU U2_BOOKDATA.SALE_PRICE TO 10
EQU U2_BOOKDATA.STOCK_LEVEL TO 11
EQU U2_BOOKDATA.MIN_ORDER TO 12
EQU U2_BOOKDATA.ON_ORDER TO 13
EQU U2_BOOKDATA.RESERVED TO 14
EQU U2_BOOKDATA.TAX_CODE TO 15
EQU U2_BOOKDATA.TAX_RATE TO 16
EQU U2_BOOKDATA.SUPPLIER_ID TO 17
EQU U2_BOOKDATA.SUPPLIER_NAME TO 18
EQU U2_BOOKDATA.PURCH_PRICE TO 19
EQU U2_BOOKDATA.LONG_DESCRIPTION TO 20


