!INCLUDE

EQU U2_BOOK.SUMMARY_TITLE_ID    TO 1
EQU U2_BOOK.SUMMARY_TITLE       To 2
EQU U2_BOOK.SUMMARY_AUTHOR_NAME To 3
EQU U2_BOOK.SUMMARY_ISBN        To 4
EQU U2_BOOK.SUMMARY_SALE_PRICE  To 5
EQU U2_BOOK.SUMMARY_MEDIA       To 6


