!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_CLIENTS
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_CLIENTS
!------------------------------------------------------------------------------
EQU U2_CLIENTS.SURNAME        TO 1
EQU U2_CLIENTS.FORENAME       TO 2
EQU U2_CLIENTS.ADDRESS        TO 3
EQU U2_CLIENTS.COUNTRY        TO 4
EQU U2_CLIENTS.TERRITORY_ID   TO 5
EQU U2_CLIENTS.JOIN_DATE      TO 6
EQU U2_CLIENTS.ACCOUNT_HELD   TO 7
EQU U2_CLIENTS.ACCOUNT_STATUS TO 7
