!INCLUDE
EQU U2_CLIENTDATA.CLIENTID    To 1
EQU U2_CLIENTDATA.FORENAME    To 2
EQU U2_CLIENTDATA.SURNAME     To 3
EQU U2_CLIENTDATA.ADDRESS     To 4
EQU U2_CLIENTDATA.COUNTRY     To 5
EQU U2_CLIENTDATA.JOINDATE    To 6
* Order summary
EQU U2_CLIENTDATA.ORDERIDS    To 10
EQU U2_CLIENTDATA.ORDERSTATUS TO 11
EQU U2_CLIENTDATA.ORDERDATE   TO 12
EQU U2_CLIENTDATA.ORDERTOTAL  To 13
* Payment summary
EQU U2_CLIENTDATA.PAYMENTIDS  To 15
EQU U2_CLIENTDATA.PAYMENTAMT  TO 16
EQU U2_CLIENTDATA.PAYMENTDATE To 17

