!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_ORDERS
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_ORDERS
!------------------------------------------------------------------------------
EQU U2_ORDERS.CLIENT_ID     TO 1
EQU U2_ORDERS.ORDER_STATUS  TO 2
EQU U2_ORDERS.DELIV_ADDR    TO 3
EQU U2_ORDERS.INSTRUCTIONS  TO 3
EQU U2_ORDERS.ORIGIN_CODE   TO 4
EQU U2_ORDERS.SHIP_ID       TO 5
EQU U2_ORDERS.SHIP_COST     TO 6
EQU U2_ORDERS.DESPATCH_DATE TO 7
EQU U2_ORDERS.SALES_ID      TO 8
EQU U2_ORDERS.BOOK_ID       TO 10
EQU U2_ORDERS.QTY           TO 11
EQU U2_ORDERS.PRICE         TO 12
EQU U2_ORDERS.PRICE_INTL    TO 12
EQU U2_ORDERS.TAX_CODE      TO 13
EQU U2_ORDERS.DESPATCHED    TO 14
EQU U2_ORDERS.PROMO_ID      TO 15
EQU U2_ORDERS.TAX_RATE      TO 16
