!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_PROFILES
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_PROFILES
!------------------------------------------------------------------------------
EQU U2_PROFILES.DEPT_GENRE TO 1
EQU U2_PROFILES.COUNTS     TO 2
