!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_PROMOTIONS
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_PROMOTIONS
!------------------------------------------------------------------------------
EQU U2_PROMOTIONS.SHORT_DESCRIPTION TO 1
EQU U2_PROMOTIONS.DISCOUNT_PCT      TO 2
EQU U2_PROMOTIONS.START_DATE        TO 3
EQU U2_PROMOTIONS.END_DATE          TO 4
EQU U2_PROMOTIONS.BOOK_ID           TO 5
EQU U2_PROMOTIONS.TITLE_ID          TO 5
EQU U2_PROMOTIONS.MIN_QTY           TO 6
