!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_PUBLISHERS
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_PUBLISHERS
!------------------------------------------------------------------------------
EQU U2_PUBLISHERS.FULLNAME TO 1
EQU U2_PUBLISHERS.BOOK_IDS TO 2
