!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_PERSONNEL
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_PERSONNEL
!------------------------------------------------------------------------------
EQU U2_PERSONNEL.SURNAME   TO 1
EQU U2_PERSONNEL.FORENAME  TO 2
EQU U2_PERSONNEL.JOB_TITLE TO 3
EQU U2_PERSONNEL.MANAGER   TO 4
