!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_PURCHASES
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_PURCHASES
!------------------------------------------------------------------------------
EQU U2_PURCHASES.ORDER_DATE     TO 1
EQU U2_PURCHASES.SUPPLIER_ID    TO 2
EQU U2_PURCHASES.SHIP_COST      TO 3
EQU U2_PURCHASES.SHIP_COST_INTL TO 3
EQU U2_PURCHASES.DELIV_DATE     TO 4
EQU U2_PURCHASES.BOOK_ID        TO 10
EQU U2_PURCHASES.ISBN           TO 11
EQU U2_PURCHASES.SUPPLIER_CODE  TO 11
EQU U2_PURCHASES.PRICE          TO 12
EQU U2_PURCHASES.PRICE_INTL     TO 12
EQU U2_PURCHASES.TAX_CODE       TO 13
EQU U2_PURCHASES.ORDER_QTY      TO 14
EQU U2_PURCHASES.RECEIVE_QTY    TO 14
EQU U2_PURCHASES.REJECT_QTY     TO 15
