!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_PARAMS
!  Generated on     : 01 JUN 2010
!  Generated by     : MakeTable script book_scripts tables
!------------------------------------------------------------------------------
