!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_PAYMENTS
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_PAYMENTS
!------------------------------------------------------------------------------
EQU U2_PAYMENTS.PAY_DATE    TO 1
EQU U2_PAYMENTS.CLIENT_ID   TO 2
EQU U2_PAYMENTS.AMOUNT      TO 3
EQU U2_PAYMENTS.AMOUNT_INTL TO 3
