!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_SALESTAX
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_SALESTAX
!------------------------------------------------------------------------------
EQU U2_SALESTAX.SHORT_DESCRIPTION TO 1
EQU U2_SALESTAX.RATE              TO 2
