!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_SHIPPING
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_SHIPPING
!------------------------------------------------------------------------------
EQU U2_SHIPPING.SHORT_DESCRIPTION TO 1
EQU U2_SHIPPING.COST              TO 2
EQU U2_SHIPPING.SHIPPER           TO 2
EQU U2_SHIPPING.BASE_RATE         TO 3
