!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_SUPPLIERS
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_SUPPLIERS
!------------------------------------------------------------------------------
EQU U2_SUPPLIERS.FULLNAME  TO 1
EQU U2_SUPPLIERS.ADDRESS   TO 2
EQU U2_SUPPLIERS.PHONE     TO 3
EQU U2_SUPPLIERS.FAX       TO 4
EQU U2_SUPPLIERS.EMAIL     TO 5
EQU U2_SUPPLIERS.SHIP_COST TO 10
