!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_TARGETS
!  Generated on     : 21 APR 2018
!  Generated by     : MakeTable script books.tables U2_TARGETS
!------------------------------------------------------------------------------
EQU U2_TARGETS.PERIOD TO 1
EQU U2_TARGETS.TARGET TO 2
