!INCLUDE
!------------------------------------------------------------------------------
!  Include file for : U2_CLIENT_ORDERS
!  Generated on     : 01 JUN 2010
!  Generated by     : MakeTable script book_scripts tables
!------------------------------------------------------------------------------
EQU U2_CLIENT_ORDERS.ORDER_IDS TO 1
